name = "brayan-api"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "brxan-portfolio"

[vars]
R2_ACCOUNT_ID = "007a29b2602ec08df62fe62163a4890f"
R2_PUBLIC_URL = "https://pub-97d4743707de4241a0db9f49705efdce.r2.dev"
SUPABASE_URL = "https://qwnefclkyuyboukkvqhb.supabase.co"
